// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Converge/Chat.tsx";

const manifest = {
  "sections": {
    "converge-chat/sections/Converge/Chat.tsx": $$$$$$0,
  },
  "name": "converge-chat",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
